# Generated by Django 4.2.7 on 2023-11-30 11:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_vendor_api_key_alter_vendor_vendor_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='api_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
